descheduler:
  deschedulerPolicy:
    strategies:
      RemoveDuplicates:
        enabled: false
      RemovePodsHavingTooManyRestarts:
        enabled: false
      RemovePodsViolatingNodeTaints:
        enabled: false
      RemovePodsViolatingNodeAffinity:
        enabled: false
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: false
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: false
      LowNodeUtilization:
        enabled: false
      HighNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
              pods: 60
  schedule: "*/5 * * * *"
