descheduler:
  deschedulerPolicy:
    strategies:
      RemoveDuplicates:
        enabled: false
      RemovePodsHavingTooManyRestarts:
        enabled: false
        params:
          podsHavingTooManyRestarts:
            podRestartThreshold: 100
            includingInitContainers: false
      RemovePodsViolatingNodeTaints:
        enabled: false
      RemovePodsViolatingNodeAffinity:
        enabled: false
        params:
          nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: false
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: false
        params:
          includeSoftConstraints: false
      HighNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            thresholds:
              cpu: 20
              memory: 40
              pods: 70
  schedule: "*/5 * * * *"
