descheduler:
  deschedulerPolicy:
    strategies:
      RemoveDuplicates:
        enabled: false
      RemovePodsHavingTooManyRestarts:
        enabled: false
      RemovePodsViolatingNodeTaints:
        enabled: false
      RemovePodsViolatingNodeAffinity:
        enabled: false
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: false
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: false
      LowNodeUtilization:
        enabled: false
      HighNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            thresholds:
              cpu: 50
              pods: 70
              memory: 50
  schedule: "*/30 * * * *"
