apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Values.provisioner.name }}
spec:
  labels:
    {{- range $key, $value := .Values.provisioner.spec.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  requirements:
    {{- range .Values.provisioner.spec.requirements }}
    - key: {{ .key | quote }}
      operator: {{ .operator | quote }}
      values:
        {{- range .values }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  limits:
    resources:
      cpu: {{ .Values.provisioner.spec.limits.resources.cpu }}
      memory: {{ .Values.provisioner.spec.limits.resources.memory }}
  providerRef:
    name: {{ .Values.provisioner.spec.providerRef.name }}
  ttlSecondsAfterEmpty: {{ .Values.provisioner.spec.ttlSecondsAfterEmpty }}
