apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: database
spec:
  hosts:
  - xquare-db.ctvh9cegfpii.ap-northeast-2.rds.amazonaws.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis
spec:
  hosts:
  - redis.xquare.app
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: NONE