operator:
  profile: default
  extensionProviders:
    - name: "xquare-middleware-grpc"
      envoyExtAuthzGrpc:
        service: "envoy-middleware-be-prod.xquare-prod.svc.cluster.local"
        port: "9000"
    - name: "sample-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "ext-authz.xquare-prod.svc.cluster.local"
        port: "9000"
  service:
    externalTrafficPolicy: Local
  hpaSpec:
    minReplicas: 2
    maxReplicas: 10
  serviceType: LoadBalancer
  servicePorts:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: helath
      port: 15020
      targetPort: 15020
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

gateway:
  servers:
  - hosts:
      - '*.xquare.app'
    port:
      name: https-xquare
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: xquare-cert
  - hosts:
      - '*.dsm-pick.com'
    port:
      name: https-pick
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: pick-cert
  - hosts:
      - '*.dsm-repo.com'
    port:
      name: https-repo
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: repo-cert

virtualServices:
  - name: argocd-server
    host: argo-cd.xquare.app
    destination:
      host: argocd-server.argocd.svc.cluster.local
      port: 80
  - name: kiali-server
    host: kiali.xquare.app
    destination:
      host: kiali.istio-system.svc.cluster.local
      port: 20001
  - name: prometeus-server
    host: prometheus.xquare.app
    destination:
      host: prometheus-server.prometheus.svc.cluster.local
      port: 80
  - name: jaeger-server
    host: jaeger.xquare.app
    destination:
      host: tracing.istio-system.svc.cluster.local
      port: 80
  - name: grafana-server
    host: grafana.xquare.app
    destination:
      host: argocd-server.argocd.svc.cluster.local
      port: 80
  - name: dex-server
    host: dex.xquare.app
    destination:
      host: dex.dex.svc.cluster.local
      port: 5556
  - name: dex-login-server
    host: dex-login.xquare.app
    destination:
      host: dex-k8s-authenticator.dex.svc.cluster.local
      port: 5555
  - name: oidc-proxy-server
    host: oidc-proxy.xquare.app
    destination:
      host: kube-oidc-proxy.dex.svc.cluster.local
      port: 443

addons:
  jeager:
    enable: true
  kiali:
    enable: true
    prometheusUrl: http://prometheus.istio-system:9090


