aws-node-termination-handler: 
  image:
    repository: 471407337433.dkr.ecr.ap-northeast-2.amazonaws.com/node-termination-handler
    tag: "v1.0.8"
  taintNode: true
  emitKubernetesEvents: true
  logLevel: debug
  webhookURLSecretName: "nth-webhook-secret"
  webhookTemplate: |
    {"summary":"Node Termination Handler","themeColor":"FF00E8","title":"Node Termination Handler Spot Interruption","sections":[{"facts":[{"name":"Description:","value":"{{ .Description }}"},{"name":"Node Name","value":"{{ .NodeName }}"},{"name":"Instance ID","value":"{{ .InstanceID }}"},{"name":"StartTime","value":"{{ .StartTime }}"}]}]}
  enableSpotInterruptionDraining: true
  enableScheduledEventDraining: true
  enableRebalanceMonitoring: true
  enableRebalanceDraining: true
  enableSqsTerminationDraining: false