aws-node-termination-handler: 
  image:
    repository: 471407337433.dkr.ecr.ap-northeast-2.amazonaws.com/node-termination-handler
    tag: "v1.0.4"
  taintNode: true
  emitKubernetesEvents: true
  logLevel: debug
  webhookURLSecretName: "nth-webhook-secret"
  webhookTemplate: |
    {
      "blocks": [
        {
          "type": "section", 
          "text": {
            "type": "mrkdwn",
            "text": "*[NTH][Instance Interruption] EventID:* `{{ .EventID }}`\n*Kind:* `{{ .Kind }}`\n*Instance:* `{{ .InstanceID }}`\n*Node:* `{{ .NodeName }}`\n*Description:* `{{ .Description }}`\n*Start Time:* `{{ .StartTime }}`"
          }
        }
      ]
    }
  enableSpotInterruptionDraining: true
  enableScheduledEventDraining: true
  enableRebalanceMonitoring: true
  enableRebalanceDraining: true
  enableSqsTerminationDraining: false