{{- range .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: istio-system
spec:
  isCA: true
  duration: 87600h # 10 years
  secretName: {{ .name }}
  commonName: {{ .commonName }}
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
    - cluster.local
    - cert-manager
  dnsNames:
    {{- range .dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  secretName: {{ .name }}
{{- end }}
