apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "kube-oidc-proxy.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - {{ .Values.istio.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kube-oidc-proxy.fullname" . }}
spec:
  hosts:
  - {{ .Values.istio.host }}
  gateways:
  - {{ include "kube-oidc-proxy.fullname" . }}
  tls:
  - match:
    - port: 443
      sniHosts:
      - {{ .Values.istio.host }}
    route:
    - destination:
        host: {{ include "kube-oidc-proxy.fullname" . }}
        port:
          number: 443
