apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xquare-cert
  namespace: xquare
spec:
  commonName: "*.xquare.app"
  dnsNames:
    - "*.xquare.app"
    - xquare.app
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  secretName: xquare-cert
