kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: xquare-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    {{- range .Values.gateway.servers }}
    - hosts: {{ .hosts | toYaml | nindent 6 }}
      port:
        name: {{ .port.name }}
        number: {{ .port.number }}
        protocol: {{ .port.protocol }}
      tls:
        mode: {{ .tls.mode }}
        credentialName: {{ .tls.credentialName }}
    {{- end }}

