name: keycloak
version: 4.10.1
appVersion: 5.0.0
description: Open Source Identity and Access Management For Modern Applications and Services
dependencies:
  - name: keycloak
    version: 18.4.3
    repository: https://codecentric.github.io/helm-charts