provisioner:
  name: xquare
  spec:
    labels:
      Karpenter: enabled    
    kubeletConfiguration:
      maxPods: 110
    requirements:
      - key: kubernetes.io/os
        operator: In
        values:
          - "linux"
      - key: "karpenter.sh/capacity-type"
        operator: In
        values:
          - "spot"
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values:
          - m5a.xlarge
          - m5a.large
          - m5.xlarge
          - m5.large
      - key: kubernetes.io/arch	
        operator: In	
        values:	
          - amd64
    limits:
      resources:
        cpu: 1k
        memory: 1000Gi
    providerRef:
      name: xquare
    ttlSecondsAfterEmpty: 20
awsNodeTemplate:
  name: xquare