provisioner:
  name: xquare
  spec:
    taints:
    - key: xquare/server
      value: true
      effect: "PreferNoSchedule"
    labels:
      Karpenter: enabled    
    kubeletConfiguration:
      maxPods: 110
    requirements:
      - key: kubernetes.io/os
        operator: In
        values:
          - "linux"
      - key: "karpenter.sh/capacity-type"
        operator: In
        values:
          - "spot"
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values:
          - m5a.xlarge
          - m5a.large
          - m5.xlarge
          - m5.large
      - key: kubernetes.io/arch	
        operator: In	
        values:	
          - amd64
    providerRef:
      name: xquare
    ttlSecondsAfterEmpty: 20
awsNodeTemplate:
  name: xquare