apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: xquare
spec:
  labels:
    team: xquare
  requirements:
    - key: kubernetes.io/os
      operator: In
      values:
        - "linux"
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
        - "spot"
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
        - "ap-northeast-2a"
        - "ap-northeast-2c"
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
        - "m5a.large"
        - "m5a.xlarge"
        - "m5a.2xlarge"
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  providerRef:
    name: xquare
  consolidation:
    enabled: true

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: xquare
spec:
  subnetSelector:
    karpenter.sh/discovery/xquare-cluster: '*'
  securityGroupSelector:
    aws:eks:cluster-name: xquare-cluster
  tags:
    karpenter.sh/discovery: xquare-cluster
