prometheus-stack:
  prometheus:
    enabled: true
    thanosService:
      enabled: true
  thanosRuler:
    enabled: true
    thanosRulerSpec:
      alertmanagersConfig:
        key: alertmanager-configs.yaml
        name: thanosruler-alertmanager-config
      objectStorageConfig:
        key: objstore.yml
        name: thanos-objstore-secret
      volumes:
        - name: object-storage
          secret:
            secretName: thanos-objstore-secret
      queryEndpoints:
      - http://global-thanos-query-dns
    extraSecret:
      name: thanosruler-alertmanager-config
      data:
        alertmanager-configs.yaml: |
          alertmanagers:
          - static_configs: ["kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local"]
            scheme: http
            timeout: 30s
            api_version: v1