aws-ebs-csi-driver: 
  controller:
    volumes:
      - name: kube-api-access
        projected:
          sources:
            - serviceAccountToken:
                expirationSeconds: 3607
                path: token
            - configMap:
                name: kube-root-ca.crt 
                items:
                  - key: ca.crt
                    path: ca.crt
            - downwardAPI:
                items:
                  - path: namespace
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
          defaultMode: 420
    volumeMounts:
      - name: kube-api-access
        readOnly: true
        mountPath: /var/run/secrets/kubernetes.io/serviceaccount