apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: global-cors
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND 
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.tcp_proxy"
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.filters.http.cors
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"
            allow_origins:
              - exact: "https://service.xquare.app"
              - exact: "https://admin.xquare.app"
              - exact: "https://admin.dsm-pick.com"
              - exact: "https://teacher.dsm-pick.com"
              - exact: "https://keeper.dsm-pick.com"
              - exact: "http://localhost:3000"
              - exact: "http://localhost:3001"
            allow_methods:
              - "GET"
              - "POST"
              - "PUT"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allow_headers: "content-type, authorization, accept, accept-encoding, Refresh-Token, X-Not-Using-Xquare-Auth"
            expose_headers:
              - "Access-Control-Allow-Credentials"