apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-peer-authentication
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: argocd-peer-authentication
  namespace: argocd
spec:
  mtls:
    mode: DISABLE