{{- range .Values.clubs }}
{{- $clubname := .name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: xquare-prod
  name: {{ $clubname }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: xquare-stag
  name: {{ $clubname }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
{{- range .users }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $clubname }}-{{ . }}-rolebinding
  namespace: xquare-prod
subjects:
- kind: User 
  name: {{ . }}
roleRef:
  kind: Role
  name: {{ $clubname }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $clubname }}-{{ . }}-rolebinding
  namespace: xquare-stag
subjects:
- kind: User 
  name: {{ . }}
roleRef:
  kind: Role
  name: {{ $clubname }}-role
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}