dex:
  config:
    issuer: https://dex.xquare.app
    logger:
      level: debug
    storage:
      type: memory
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true 
    staticClients:
    - id: xquare
      name: 'xquare'
      redirectURIs:
        - 'https://dex-login.xquare.app/callback'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: d486635d82817cb24ce9
        clientSecret: 792b92a7326af17adeed34241ae95bbd98c1785a
        redirectURI: 'https://dex.xquare.app/callback'