apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: api-ingress
  namespace: be-prod
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: api.xquare.app
    tls:
      secretName: be-prod-cert
    authorization:
      extensionRef:
        name: contour-middleware
        namespace: be-prod
    corsPolicy:
      allowCredentials: true
      allowOrigin: 
        - "https://service.xquare.app"
      allowMethods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowHeaders:
        - "content-type"
        - "authorization"
        - "accept"
        - "accept-encoding"
      exposeHeaders:
        - "Access-Control-Allow-Credentials"
  includes:
    - name: dms
      namespace: be-prod
    - name: application
      namespace: be-prod
    - name: meal
      namespace: be-prod
    - name: notification
      namespace: be-prod
    - name: backoffice
      namespace: be-stag
    - name: user
      namespace: be-prod
    - name: authority
      namespace: be-prod
    - name: oauth
      namespace: be-prod
