apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: stag-api-ingress
  namespace: be-stag
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: stag-api.xquare.app
    tls:
      secretName: be-stag-cert
    authorization:
      extensionRef:
        name: contour-middleware
        namespace: be-stag
    corsPolicy:
      allowCredentials: true
      allowOrigin: 
        - "http://localhost:3000"
        - "http://localhost:3001"
        - "https://service.xquare.app"
        - "https://admin.xquare.app"
      allowMethods:
        - "GET"
        - "POST"
        - "PUT"
        - "PATCH"
        - "DELETE"
        - "OPTIONS"
      allowHeaders:
        - "content-type"
        - "authorization"
        - "accept-encoding"
        - "accept"
        - "Refresh-Token"
      exposeHeaders:
        - "Access-Control-Allow-Credentials"
  includes:
    - name: application
      namespace: be-stag
    - name: meal
      namespace: be-stag
    - name: backoffice
      namespace: be-stag
    - name: user
      namespace: be-stag
    - name: authority
      namespace: be-stag
    - name: contour-middleware-test
      namespace: be-stag
    - name: attachment
      namespace: be-stag
    - name: point
      namespace: be-stag
    - name: feed
      namespace: be-stag
    - name: pick
      namespace: be-stag
    - name: timetable
      namespace: be-stag
    - name: schedule
      namespace: be-stag
    - name: report
      namespace: be-stag
    - name: notification
      namespace: be-stag
