karpenter:
  hostNetwork: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ""
  clusterName: ""
  clusterEndpoint: ""
  aws:
    defaultInstanceProfile: ""
  replica: 1
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi