karpenter:
  hostNetwork: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ""
  clusterName: ""
  clusterEndpoint: ""
  aws:
    defaultInstanceProfile: ""
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  nodeSelector:
    Karpenter: enabled
  tolerations:
  - effect: "NoSchedule"
    key: karpenter
    operator: "Equal"
    value: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: In
                values:
                - xquare