karpenter:
  hostNetwork: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ""
  clusterName: ""
  clusterEndpoint: ""
  aws:
    defaultInstanceProfile: ""
  nodeSelector:
    Karpenter: enabled
  tolerations:
  - effect: "NoSchedule"
    key: karpenter
    operator: "Equal"
    value: "true"