cert-manager:
  nodeSelector:
    Karpenter: enabled
  tolerations:
  - effect: "NoSchedule"
    key: karpenter
    operator: "Equal"
    value: "true"
  cainjector:
    enabled: true
    nodeSelector:
      Karpenter: enabled
    tolerations:
    - effect: "NoSchedule"
      key: karpenter
      operator: "Equal"
      value: "true"
  webhook:
    nodeSelector:
      Karpenter: enabled
    tolerations:
    - effect: "NoSchedule"
      key: karpenter
      operator: "Equal"
      value: "true"