loki:
  isDefault: false
  url: http://loki-stack:3100
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  serviceAccount:
    create: true
    name: xquare-loki
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::471407337433:role/loki_s3_role 
      eks.amazonaws.com/sts-regional-endpoints: "true"
  monitoring:
    selfMonitoring:
      grafanaAgent:
        installOperator: false
  backend:
    replicas: 1
    persistence:
      enabled: false
  write:
    replicas: 1
    persistence:
      enabled: false
  read:
    replicas: 1
    persistence:
      enabled: false
  loki:
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    storage:
      bucketNames:
        chunks: xquare-loki-bucket
        ruler: xquare-loki-bucket
        admin: xquare-loki-bucket
    storage_config:
      aws:
        s3: s3://ap-northeast-2/xquare-loki-bucket
        region: ap-northeast-2
      boltdb_shipper:
        active_index_directory: /var/loki/active
        shared_store: s3
        cache_location: /var/loki/cache
        cache_ttl: 24h
    compactor:
      working_directory: /var/loki/compactor
      shared_store: s3
    schema_config:
      configs:
        - object_store: s3
          index:
            period: 24h
          chunks:
            period: 24h
    limits_config:
      retention_period: 7d
    compactor:
      retention_enabled: true
    table_manager:
      retention_deletes_enabled: true
      retention_period: 7d

promtail:
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki-stack:3100/loki/api/v1/push
  snippets:
    scrapeConfigs: |
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __tmp_controller_name
              - __meta_kubernetes_pod_name
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              - __meta_kubernetes_pod_label_release
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: instance
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              - __meta_kubernetes_pod_label_component
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: component
          - replacement: kubernetes-pods
            target_label: scrape_job
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: xquare-prod|xquare-stag|spot-handler