{{- range .Values.clubs }}
{{- $clubname := .name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: xquare-prod
  name: {{ $clubname }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
  resourceNames:
  {{- range .projects }}
    - {{ . }}-fe-prod
    - {{ . }}-be-prod
  {{- end }}
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: xquare-stag
  name: {{ $clubname }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
  resourceNames:
  {{- range .projects }}
    - {{ . }}-fe-stag
    - {{ . }}-be-stag
  {{- end }}
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
{{- range .users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $clubname }}-{{ . }}
  namespace: xquare-prod
subjects:
- kind: User 
  name: {{ . }}
roleRef:
  kind: Role
  name: {{ $clubname }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $clubname }}-{{ . }}
  namespace: xquare-stag
subjects:
- kind: User 
  name: {{ . }}
roleRef:
  kind: Role
  name: {{ $clubname }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}