apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
profiles:
  - name: xquare-descheduler
    pluginConfig:
      - name: {{ .Values.descheduler.strategies.LowNodeUtilization.name }}
        args:
          thresholds:
            "cpu": {{ .Values.descheduler.strategies.LowNodeUtilization.args.thresholds.cpu }}
            "memory": {{ .Values.descheduler.strategies.LowNodeUtilization.args.thresholds.memory }}
            "pods": {{ .Values.descheduler.strategies.LowNodeUtilization.args.thresholds.pods }}
            targetThresholds:
              "cpu": {{ .Values.descheduler.strategies.LowNodeUtilization.args.targetThresholds.cpu }}
              "memory": {{ .Values.descheduler.strategies.LowNodeUtilization.args.targetThresholds.memory }}
              "pods": {{ .Values.descheduler.strategies.LowNodeUtilization.args.targetThresholds.pods }}
      - name: {{ .Values.descheduler.strategies.PodLifeTime.name}}
        args:
          maxPodLifeTimeSeconds: {{ .Values.descheduler.strategies.PodLifeTime.args.maxPodLifeTimeSeconds }}
            states:
              {{-range .Values.descheduler.strategies.PodLifeTime.args.states}}
            {{- end}}
    plugins:
      balance:
        enabled:
          - {{ .Values.descheduler.strategies.LowNodeUtilization.name }}
          - {{ .Values.descheduler.strategies.PodLifeTime.name }}
