argo-cd:
  configs:
    params:
      server.insecure: true 
  global:
    nodeSelector:
      Karpenter: enabled
    tolerations:
    - effect: "NoSchedule"
      key: karpenter
      operator: "Equal"
      value: "true"