kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-nth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-nth
subjects:
  - kind: ServiceAccount
    name: aws-nth
    namespace: {{ .Release.Namespace }}