name: Check Helm Chart Version

on:
  push:
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get updated chart name and version
        run: |
          git diff --name-only HEAD^ HEAD | grep Chart.yaml | while read line; do
              CHART=$(grep '^name: ' $line | cut -d ' ' -f 2)
              VERSION=$(grep '^version: ' $line | cut -d ' ' -f 2)

              if [ -z "$CHART" ] || [ -z "$VERSION" ]; then
                  continue
              fi

              echo "$CHART=$VERSION" >> matrix.txt
          done
        shell: bash

      - name: Upload matrix.txt
        uses: actions/upload-artifact@v2
        with:
          name: matrix
          path: matrix.txt

  dispatches:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - name: Download matrix.txt
        uses: actions/download-artifact@v2
        with:
          name: matrix

      - name: Send Repository Dispatches
        run: |
          while IFS='=' read -r CHART VERSION; do
            echo "::set-output name=chart::$CHART"
            echo "::set-output name=version::$VERSION"
          done < matrix/matrix.txt
        id: matrix
        shell: bash

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: pokabook/xquare-infrastructure-global
          event-type: chart-update
          client-payload: |
            {
              "chart" : "${{ steps.matrix.outputs.chart }}",
              "version" : "${{ steps.matrix.outputs.version }}"
            }
