name: Check Helm Chart Version

on:
  push:
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Identify updated charts
        id: set-matrix
        run: |
          CHARTS=$(git diff --name-only HEAD^ HEAD | grep Chart.yaml | while read line; do
            CHART=$(grep '^name: ' $line | cut -d ' ' -f 2)
            VERSION=$(grep '^version: ' $line | cut -d ' ' -f 2)
            echo "{\"chart\":\"$CHART\", \"version\":\"$VERSION\"},"
          done | sed 's/.$//')
          echo "::set-output name=matrix::{\"include\":[$CHARTS]}"

  repository-dispatch:
    needs: check-version
    strategy:
      matrix: ${{fromJson(needs.check-version.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: team-xquare/xquare-infrastructure-global
          event-type: chart-update
          client-payload: '{"chart": "${{ matrix.chart }}", "version": "${{ matrix.version }}" }'
