name: Check Helm Chart Version
on:
  push:
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get chart name and version
        id: chart
        run: |
          git diff --name-only HEAD^ HEAD | grep Chart.yaml | while read line; do
            CHART=$(grep '^name: ' $line | cut -d ' ' -f 2)
            VERSION=$(grep '^version: ' $line | cut -d ' ' -f 2)
            if [ ! -z "$VERSION" ]; then
              echo "::set-output name=chart::$CHART"
              echo "::set-output name=version::$VERSION"
              break
            fi
          done

      - name: Trigger workflow in another repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: pokabook/xquare-infrastructure-global
          event-type: chart-update
          client-payload: '{"chart": "${{ steps.chart.outputs.chart }}", "version": "${{ steps.chart.outputs.version }}"}'
