name: Check Helm Chart Version
on:
  push:
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get updated chart name and version
        run: |
          git diff --name-only HEAD^ HEAD | grep Chart.yaml | while read line; do
            CHART=$(grep '^name: ' $line | cut -d ' ' -f 2)
            VERSION=$(grep '^version: ' $line | cut -d ' ' -f 2)
            echo "$CHART = $VERSION"
            curl -X POST -H "Authorization: token ${{ secrets.TOKEN }}" \
                 -d '{"event_type": "chart-update", "client_payload": {"chart": "'$CHART'", "version": "'$VERSION'"}}' \
                 https://api.github.com/repos/pokabook/xquare-infrastructure-global/dispatches
          done
