name: Check Helm Chart Version

on:
  push:
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get updated chart name and version
        id: charts
        run: |
          git diff --name-only HEAD^ HEAD | grep Chart.yaml | while read line; do
              CHART=$(grep '^name: ' $line | cut -d ' ' -f 2)
              VERSION=$(grep '^version: ' $line | cut -d ' ' -f 2)

              if [ -z "$CHART" ] || [ -z "$VERSION" ]; then
                  continue
              fi

              echo "$CHART=$VERSION" >> matrix.txt
          done
          cat matrix.txt
          MATRIX=$(awk -F'=' '{print "\"" $1 "\": \"" $2 "\""}' matrix.txt | paste -sd, - | sed 's/^/{/;s/$/}/')
          echo "::set-output name=matrix::$MATRIX"
          echo "Matrix: $MATRIX"

  dispatches:
    needs: check-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    matrix:
      chart: ${{fromJson(needs.check-version.outputs.charts)}}
   
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ env.XQUARE_ACTION_GHP_TOKEN }}
          repository: pokabook/xquare-infrastructure-global
          event-type: chart-update
          client-payload: |
            {
              "chart" : "${{ matrix.chart }}", 
              "image_tag" : "$${{ matrix.version }}"
            }
