## Reference: https://github.com/helm/chart-releaser-action
name: Chart Publish
on:
  push:
    branches:
      - main
    paths:
      - "helm/**"

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.10.1

      - name: Add helm repo
        run: |
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Helm build
        run: |
          changed_helm_packages=$(git diff --name-only HEAD~1 | grep '^helm/' | cut -d/ -f1-2)
          while IFS=$'\n' read -r package_directory; do
              helm dependency build $package_directory
              helm package $package_directory
          done <<< "$changed_helm_packages"

      - name: checkout gh-pages branch and helm index
        run: | 
          git checkout gh-pages --
          helm repo index .

      - name: Commit The Chart Realease
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          commit_options: '--no-verify --signoff'
          branch: gh-pages
          skip_checkout: true
          repository: .
          commit_user_name: XQUARE GitOps Bot
          commit_user_email: teamxquare@gmail.com
          commit_author: XQUARE GitOps Bot <teamxquare@gmail.com>
