thanos:
  existingObjstoreSecret: thanos-objstore-secret
  query:
    enabled: true
    stores: 
    - kube-prometheus-stack-thanos-discovery:10901
    service:
      type: ClusterIP
      ports:
        http: 9090
  queryFrontend:
    enabled: true
    config: |-
      type: IN-MEMORY
      config:
        max_size: 512MB
        max_size_items: 100
        validity: 100s
    service:
      type: ClusterIP
      ports:
        http: 9090
  bucketweb:
    enabled: true
  compactor:
    enabled: true
    retentionResolutionRaw: 30d
    retentionResolution5m: 30d
    retentionResolution1h: 10y
    consistencyDelay: 30m
    persistence:
      enabled: false
  storegateway:
    enabled: true
    persistence:
      enabled: false