thanos:
  existingObjstoreSecret: thanos-objstore-secret
  query:
    enabled: true
    stores: 
    - kube-prometheus-stack-thanos-discovery:10901
    service:
      type: ClusterIP
      ports:
        http: 9090
  queryFrontend:
    enabled: true
    service:
      type: ClusterIP
      ports:
        http: 9090
  bucketweb:
    enabled: false
  compactor:
    enabled: true
    retentionResolutionRaw: 30d
    retentionResolution5m: 30d
    retentionResolution1h: 10y
    consistencyDelay: 30m
    persistence:
      enabled: false
  storegateway:
    enabled: true
    persistence:
      enabled: false
    serviceAccount:
      create: true
      name: "xquare-thanos-storegateway"
      automountServiceAccountToken: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::471407337433:role/thanos_s3_role 