thanos:
  objstoreConfig: |-
    type: s3
    config:
      bucket: "xquare-thanos-bucket"
      endpoint: "s3.ap-northeast-2.amazonaws.com"
      aws_sdk_auth: true
  query:
    enabled: true
    stores: 
    - 172.20.23.225:10901
    service:
      type: ClusterIP
      ports:
        http: 9090
  queryFrontend:
    enabled: true
    config: |-
      type: IN-MEMORY
      config:
        max_size: 512MB
        max_size_items: 100
        validity: 100s
    service:
      type: ClusterIP
      ports:
        http: 9090
  bucketweb:
    enabled: true
  compactor:
    enabled: true
    retentionResolutionRaw: 30d
    retentionResolution5m: 30d
    retentionResolution1h: 10y
    consistencyDelay: 30m # Compaction 실행주기 설정 
  storegateway:
    enabled: true
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::471407337433:role/thanos_s3_role
    persistence:
      enabled: false
  compactor:
    enabled: false
    retentionResolutionRaw: 30d
    retentionResolution5m: 30d
    retentionResolution1h: 10y
    consistencyDelay: 15m