thanos:
  query:
    enabled: true
  storegateway:    
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::471407337433:role/thanos_s3_role
    enabled: true
    persistence:
      enabled: false
    logLevel: debug
  receive:
    enabled: true
    persistence:
      enabled: false
  objstoreConfig: |
    type: s3
    config:
      bucket: "xquare-thanos-bucket"
      endpoint: "s3.ap-northeast-2.amazonaws.com"
      aws_sdk_auth: true
  stores: 
  - kube-prometheus-stack-thanos-discovery:10901
  compactor:
    enabled: false
    retentionResolutionRaw: 30d
    retentionResolution5m: 30d
    retentionResolution1h: 10y
    consistencyDelay: 15m